#ifndef X6_ERRNO_H_
#define X6_ERRNO_H_

enum X6_STATUS {
  X6_OK,
  X6_UNKNOWN_ERROR = -1,
  X6_NO_DEVICE_FOUND = -2,
  X6_UNCONNECTED = -3,
  X6_INVALID_FREQUENCY = -4,
  X6_TIMEOUT = -5,
  X6_INVALID_CHANNEL = -6,
  X6_FILE_ERROR = -7,
  X6_INVALID_FRAMESIZE = -8
};

#endif
