#!/bin/bash

# Creates the Matlab compatible version of the header file

cp ../lib/libx6.h libx6.matlab.h

#Change the path to the includes
#Remove unexported update_log function
#Remove complex header and _Complex types

sed -i '
s/^#include "X6/#include "..\/lib\/X6/g
/^#undef I/d
/^X6_STATUS update_log/d' libx6.matlab.h
